// MODAL
export const LOGIN_MODAL_TOGGLE = "LOGIN_MODAL_TOGGLE";
export const REGISTER_MODAL_TOGGLE = "REGISTER_MODAL_TOGGLE";

// AUTH
export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
